$FND_TOP/bin/FNDLOAD apps/apps 0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct AR_BATCHES.ldt DESC_FLEX APPLICATION_SHORT_NAME=AR DESCRIPTIVE_FLEXFIELD_NAME='AR_BATCHES'

$FND_TOP/bin/FNDLOAD apps/apps 0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct AR_BATCH_SOURCES.ldt DESC_FLEX APPLICATION_SHORT_NAME=AR DESCRIPTIVE_FLEXFIELD_NAME='AR_BATCH_SOURCES'

$FND_TOP/bin/FNDLOAD apps/apps 0 Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct AR_MEMO_LINES.ldt DESC_FLEX APPLICATION_SHORT_NAME=AR DESCRIPTIVE_FLEXFIELD_NAME='AR_MEMO_LINES'
