#!/usr/bin/ksh

. ~/.profile

MAILLIST_ALL=slava.mavashev@tnuva.co.il

DATE=`date +"%d-%b-%Y-%H%M"`
ALL_REPORTS="/tmp"
APPSPWD=`env|grep APPLPWD= |awk -F= '{print $2}'`

sqlplus -s <<!
APPS/$APPSPWD


col CONCURRENT_QUEUE_NAME format a18 heading 'Manager'
col sdate format a12 heading 'Start Time'
col REQUEST_ID format 99999999 heading 'ReqID'
col USER_CONCURRENT_PROGRAM_NAME format a40 heading 'Program Name'
col state format a7 heading 'State'
set pagesize 10000
set linesize 100

select To_Char(Actual_Start_Date, 'DD-MON HH24:MI') sdate,
REQUEST_ID,CONCURRENT_QUEUE_NAME,
      DECODE (DESCRIPTION,
      NULL,
      USER_CONCURRENT_PROGRAM_NAME,
      DESCRIPTION||' ('||USER_CONCURRENT_PROGRAM_NAME||')')
USER_CONCURRENT_PROGRAM_NAME ,
       decode(phase_code,'R','Running','P','Pending','Other') state
from FND_CONCURRENT_WORKER_REQUESTS 
where PHASE_CODE != 'C'
and hold_flag <> 'Y'
and   requested_start_date <= sysdate
order by Actual_Start_Date
/
exit

