#!/usr/bin/ksh

. ~/.profile

MAILLIST_ALL=slava.mavashev@tnuva.co.il

DATE=`date +"%d-%b-%Y-%H%M"`
ALL_REPORTS="/tmp"
SPOOL=$ALL_REPORTS/JDBC_$DATE.lst
APPSPWD=`env|grep APPLPWD= |awk -F= '{print $2}'`

sqlplus -s <<!
APPS/$APPSPWD
spool $SPOOL
select to_char(SYSDATE,'dd/mm/yy hh24') from dual;

@/u01_share/DBA/scripts/MON/monitor_jdbc_conn.sql
@/u01_share/DBA/scripts/MON/monitor.sql
spool off
/
exit
!



echo ""
echo ""
echo "Status as of `date`"
echo ""

cat $SPOOL >> /u01_share/DBA/scripts/MON/monitor_jdbc_conn_report.txt
rm  $SPOOL
