SELECT IL.BATCH_SOURCE_NAME || ',' || IL.HEADER_ATTRIBUTE12 || ',' || IL.ORG_ID, LV.description,   COUNT(1)
  FROM XXAR_INTERFACE_LINES_ALL_HIST IL, FND_LOOKUP_VALUES_VL LV
 WHERE IL.CREATION_DATE >= SYSDATE - 3
   AND LV.LOOKUP_CODE = IL.ORG_ID
   AND LV.LOOKUP_TYPE = 'XXAR_INTERFACE_NOTIFICATIONS'
   AND IL.STATUS_CODE = '3'
 GROUP BY IL.BATCH_SOURCE_NAME || ',' || IL.HEADER_ATTRIBUTE12 || ',' || IL.ORG_ID, LV.description
/
