XXHRCVDI           1 N       exec WF_PURGE.NOTIFICATIONS('XXHRCVDI',SYSDATE,FALSE);

AZNM000            1 Y       exec WF_PURGE.NOTIFICATIONS('AZNM000',SYSDATE,FALSE);

JTFTASK            3 N       exec WF_PURGE.NOTIFICATIONS('JTFTASK',SYSDATE,FALSE);


AZNM000            1 Y       exec WF_PURGE.NOTIFICATIONS('AZNM000',SYSDATE,FALSE);

JTFTASK            3 N       exec WF_PURGE.NOTIFICATIONS('JTFTASK',SYSDATE,FALSE);

OEOL               3 N       exec WF_PURGE.NOTIFICATIONS('OEOL',SYSDATE,FALSE);

OKSWARWF           4 N       exec WF_PURGE.NOTIFICATIONS('OKSWARWF',SYSDATE,FALSE);

PORCPT             6 Y       exec WF_PURGE.NOTIFICATIONS('PORCPT',SYSDATE,FALSE);

POERROR            7 N       exec WF_PURGE.NOTIFICATIONS('POERROR',SYSDATE,FALSE);

WFERROR            9 N       exec WF_PURGE.NOTIFICATIONS('WFERROR',SYSDATE,FALSE);

JTF_APPR          10 Y       exec WF_PURGE.NOTIFICATIONS('JTF_APPR',SYSDATE,FALSE);

JTF_APPR          14 N       exec WF_PURGE.NOTIFICATIONS('JTF_APPR',SYSDATE,FALSE);

MRPEXWFS          19 Y       exec WF_PURGE.NOTIFICATIONS('MRPEXWFS',SYSDATE,FALSE);



OKCAUKAP          42 Y       exec WF_PURGE.NOTIFICATIONS('OKCAUKAP',SYSDATE,FALSE);

CTOCHORD          68 Y       exec WF_PURGE.NOTIFICATIONS('CTOCHORD',SYSDATE,FALSE);


OKCAUKAP          42 Y       exec WF_PURGE.NOTIFICATIONS('OKCAUKAP',SYSDATE,FALSE);

CTOCHORD          68 Y       exec WF_PURGE.NOTIFICATIONS('CTOCHORD',SYSDATE,FALSE);

CS_MSGS          109 N       exec WF_PURGE.NOTIFICATIONS('CS_MSGS',SYSDATE,FALSE);

XDPWFSTD         159 N       exec WF_PURGE.NOTIFICATIONS('XDPWFSTD',SYSDATE,FALSE);

OKCAUKAP         290 N       exec WF_PURGE.NOTIFICATIONS('OKCAUKAP',SYSDATE,FALSE);

XXARNCST         347 Y       exec WF_PURGE.NOTIFICATIONS('XXARNCST',SYSDATE,FALSE);

XXAUSEND         382 Y       exec WF_PURGE.NOTIFICATIONS('XXAUSEND',SYSDATE,FALSE);

GLGISNTF         505 Y       exec WF_PURGE.NOTIFICATIONS('GLGISNTF',SYSDATE,FALSE);

POERROR          751 Y       exec WF_PURGE.NOTIFICATIONS('POERROR',SYSDATE,FALSE);

APVRMDER        1010 Y       exec WF_PURGE.NOTIFICATIONS('APVRMDER',SYSDATE,FALSE);

XXHRCVDI        2836 Y       exec WF_PURGE.NOTIFICATIONS('XXHRCVDI',SYSDATE,FALSE);



FNDCMMSG        5031 Y       exec WF_PURGE.NOTIFICATIONS('FNDCMMSG',SYSDATE,FALSE);


FNDCMMSG        5031 Y       exec WF_PURGE.NOTIFICATIONS('FNDCMMSG',SYSDATE,FALSE);

POAPPRV         6995 N       exec WF_PURGE.NOTIFICATIONS('POAPPRV',SYSDATE,FALSE);

REQAPPRV        7295 N       exec WF_PURGE.NOTIFICATIONS('REQAPPRV',SYSDATE,FALSE);

FNDCMMSG       13504 N       exec WF_PURGE.NOTIFICATIONS('FNDCMMSG',SYSDATE,FALSE);

MSCEXPWF       13948 Y       exec WF_PURGE.NOTIFICATIONS('MSCEXPWF',SYSDATE,FALSE);

POAPPRV        14196 Y       exec WF_PURGE.NOTIFICATIONS('POAPPRV',SYSDATE,FALSE);

REQAPPRV       16159 Y       exec WF_PURGE.NOTIFICATIONS('REQAPPRV',SYSDATE,FALSE);

XXCSNOT        33099 N       exec WF_PURGE.NOTIFICATIONS('XXCSNOT',SYSDATE,FALSE);

WFERROR        74300 Y       exec WF_PURGE.NOTIFICATIONS('WFERROR',SYSDATE,FALSE);
